# Generated by Django 3.2.6 on 2021-09-02 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transcriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='conversation_id',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='job_id',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='zip_file',
            field=models.FileField(blank=True, upload_to='zip_files/'),
        ),
    ]
