# Generated by Django 3.2.6 on 2021-09-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0002_auto_20210902_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='media_type',
            field=models.CharField(choices=[('text', 'text'), ('audio', 'audio'), ('video', 'video')], default='text', max_length=5),
            preserve_default=False,
        ),
    ]
