# Generated by Django 3.2.6 on 2021-09-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0003_document_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='media_type',
            field=models.CharField(choices=[('text', 'text'), ('audio', 'audio'), ('video', 'video'), ('audio url', 'audio url'), ('video url', 'video url')], max_length=10),
        ),
    ]
