# Generated by Django 3.2.6 on 2021-08-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='app_id',
            field=models.CharField(help_text='Enter App ID', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='secret_id',
            field=models.CharField(help_text='Enter Secret ID', max_length=250, unique=True),
        ),
    ]
